dna_varejo_home:
    resource: "@DNAVarejoHomeBundle/Controller/"
    type:     annotation
    prefix:   /

dna_varejo_client:
    resource: "@DNAVarejoCoreBundle/Controller/"
    type:     annotation
    prefix:   /

